package com.codexisland.android.shell.bootstrap

data class ShellBootstrapUiState(
    val deviceName: String,
    val hostConnectionInput: String,
    val hostDisplayName: String,
    val authToken: String,
    val pairingCode: String,
    val subtitle: String,
    val runtimeStatus: String,
    val engineStatus: String,
    val bindingSurface: String,
    val connection: String,
    val commandQueue: String,
    val pairedDevices: String,
    val reconnect: String,
    val diagnostics: String,
    val lastError: String,
    val helloCommandPreview: String,
    val pairStartPreview: String,
    val pairConfirmPreview: String,
    val reconnectPreview: String,
    val nextSteps: String,
    val authTokenHelper: String,
    val hostProfilesSummary: String,
    val activeHostSummary: String,
)
